#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           FL,            tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           FR,            tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port4,           BR,            tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port5,           BL,            tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_4)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------

	Motor Pin Diagram:

	FL - front left motor
	FR - front right motor
	BR - back right motor
	BL - back left motor

	Motion / Mechanics Notes

	Entire left side is reversed so that robot can go forward
	List (FL Speed, BL speed, BR speed, FR) - remember FL and BL are reversed
	Forward: 127, 127, 127, 127 - both joysticks forward
	Backwards: -127, -127, -127, -127 - both joysticks backwards
	Strafe Left: -127, 127, 127, -127 - both joysticks left
	Strafe Right: 127, -127, -127, 127 - both joysticks right
	Rotate Left: -127, -127, 127, 127 - left joystick down right joystick up
	Rotate Right: 127, 127, -127,-127 - left joystick up right joystick down


------------------------------------------------------*/

task main()
{
	while(true){

	// Normal Tank Controls
	motor[FR] = vexRT[Ch2];
	motor[BR] = vexRT[Ch2];
	motor[FL] = vexRT[Ch3];
	motor[FR] = vexRT[Ch3];

	//Strafing Controls <- ->
	motor[FR] = vexRT[Ch1];
	motor[FL] = vexRT[Ch1];
	motor[BR] = vexRT[Ch4];
	motor[BL] = vexRT[Ch4];
	}



}
