#pragma config(Motor,  port1,           one,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           two,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           three,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           four,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           five,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           six,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           seven,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           eight,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           nine,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          ten,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int globalSpeed = 50;
task main()
{
	while(true){
	motor[one] = globalSpeed;
	motor[two] = globalSpeed;
	motor[three] = globalSpeed;
	motor[four] = globalSpeed;
	motor[five] = globalSpeed;
	motor[six] = globalSpeed;
	motor[seven] = globalSpeed;
	motor[eight] = globalSpeed;
	motor[nine] = globalSpeed;
	motor[ten] = globalSpeed;

	}



}
