#pragma config(Motor,  port1,           one,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           two,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           three,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           four,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           five,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           six,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           seven,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           eight,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           nine,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          ten,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
	motor[one] = 127;
	motor[two] = 127;
	motor[three] = 127;
	motor[four] = 127;
	motor[five] = 127;
	motor[six] = 127;
	motor[seven] = 127;
	motor[eight] = 127;
	motor[nine] = 127;
	motor[ten] = 127;

	}



}
