#pragma config(Motor,  port2,           armMtr1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           armMtr2,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           FL,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           FR,            tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           BR,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           BL,            tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           clawMtr,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------

By Wyatt Johnson. Used on robot 1900W of the Woodward Academy Robotics Team

Motion / Mechanics Notes

Entire left side is reversed so that robot can go forward
List (FL Speed, BL speed, BR speed, FR) - remember FL and BL are reversed
Forward: 127, 127, 127, 127 - both joysticks forward
Backwards: -127, -127, -127, -127 - both joysticks backwards
Strafe Left: -127, 127, 127, -127 - both joysticks left
Strafe Right: 127, -127, -127, 127 - both joysticks right
Rotate Left: -127, -127, 127, 127 - left joystick down right joystick up
Rotate Right: 127, 127, -127,-127 - left joystick up right joystick down

Button Controls

6U - raise arm
6D - lower arm

5U - open claw
5D - close claw




------------------------------------------------------*/

int threshold = 15; //minimum joystick value
int armPwr = 80;
int clawPwr = 100;

task main()
{
	int LY = 0;
	int LX = 0;
	int RY = 0;
	int RX = 0;

	while(true )
	{
		/*
		Ternary Statement: value = (true boolean) ? (false boolean) : value
		If the absolute value of one of these vexRT Channels is greater than the threshold, assign the value
		If it is NOT greater than threshold, make it 0
		*/
		LX = (abs(vexRT[Ch4]) > threshold) ? vexRT[Ch4] : 0;
		LY = (abs(vexRT[Ch3]) > threshold) ? vexRT[Ch3] : 0;
		RY = (abs(vexRT[Ch2]) > threshold) ? vexRT[Ch2] : 0;
		RX = (abs(vexRT[Ch1]) > threshold) ? vexRT[Ch1] : 0;

		motor[FL] = LY + LX;
		motor[FR] = RY - RX;
		motor[BR] = RY + RX;
		motor[BL] = LY - LX;

		//Arm Controls
		if(vexRT[Btn6U] == 1){ //press 6U to raise bar
		motor[armMtr1] = armPwr;
		motor[armMtr2] = armPwr;
		}
		else if (vexRT[Btn6D] == 1){ //press 6D to lower bar
		motor[armMtr1] = -armPwr;
		motor[armMtr2] = -armPwr;

		}
		else if (vexRT[Btn5U] == 1){
		motor[clawMtr] = clawPwr;
		}
		else if(vexRT[Btn5D] = 1){
		motor[clawMtr] = -clawPwr;
		}
		else { //if no button is pressed, motors stall (hold bar, but damages motor)
		motor[armMtr1] = 10;
		motor[armMtr2] = 10;
		motor[clawMtr] = 20;
		}

	}
}
