#pragma config(Motor,  port4,           leftHang,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightHang,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void sethangmotors (int power) {
	motor[leftHang] = power;
	motor[rightHang] = power;
}

task main()
{
	while(1) {
		sethangmotors(vexRT[Btn6U]*127 - vexRT[Btn6D]*127);
	}

}
