#pragma config(Sensor, dgtl1,  drumLock,       sensorDigitalOut)
#pragma config(Sensor, dgtl2,  drumPosEnc,     sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  activateDebug,  sensorTouch)
#pragma config(Sensor, dgtl5,  drumZero,       sensorTouch)
#pragma config(Sensor, dgtl12, stop,           sensorTouch)
#pragma config(Motor,  port1,           lDriveFront,   tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           lDriveBack,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           rCatapult1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rCatapult2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rCatapult3,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lCatapult1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lCatapult2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lCatapult3,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rDriveFront,   tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rDriveBack,    tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setDrumMotors (float power) {
	motor[lCatapult1] = power;
	motor[lCatapult2] = power;
	motor[lCatapult3] = power;
	motor[rCatapult1] = power;
	motor[rCatapult2] = power;
	motor[rCatapult3] = power;
}

void setLeftDtMotors(float power) {
	motor[lDriveFront] = power;
	motor[lDriveBack] = power;
}

void setRightDtMotors(float power) {
	motor[rDriveFront] = power;
	motor[rDriveBack] = power;
}

//full rev = 360*7
//FORWARD ONLY - this function is not written to handle negative values yet and the drum will only go forward
//automatically releases ratchet first
void moveCatapultDrumDist (int encoderClicks) {
	SensorValue[drumLock] = 1;
	SensorValue[drumPosEnc] = 0;
	wait1Msec(250);
	time1[T1] = 0;
	writeDebugStreamLine("Start time: %f", time1[T1]);
	while(abs(SensorValue[drumPosEnc]) < encoderClicks) {
		setDrumMotors(127);
		writeDebugStreamLine("E: %f, T: %f", SensorValue[drumPosEnc], time1[T1]);
		wait1Msec(250);
	}
	writeDebugStreamLine("End time: %f", time1[T1]);
	setDrumMotors(0);
}

// !!!LIFT RATCHET FIRST!!!
void resetDrumPosition() {
	wait1Msec(1000); //one second to make sure the human has lifted the ratchet
	while (!SensorValue[drumZero]) {
		setDrumMotors(-127);
	}
	setDrumMotors(0);
}

void runDebugCode() {
	writeDebugStreamLine("Encoder start position: %d",SensorValue[drumPosEnc]);
	moveCatapultDrumDist(340);
	writeDebugStreamLine("Encoder end position: %d",SensorValue[drumPosEnc]);
}

bool DEBUG_ENABLE = true;

task main()
{
	//moveCatapultDrumDist(360)
	//int reverse = 1;
	//setDrumMotors(127*reverse);
	//runDebugCode()
	bLCDBacklight = true;
	clearLCDLine(0);
	if (DEBUG_ENABLE && SensorValue[activateDebug] && false) {
		writeDebugStreamLine("Started")
		wait1Msec(2000);
		SensorValue[drumPosEnc] = 0;
		time1[T1] = 0;
		writeDebugStreamLine("E: %f, T: %f", SensorValue[drumPosEnc], time1[T1]);
		moveCatapultDrumDist(360*14);
		} else {
			int LY = 0;
			int LX = 0;
			int RY = 0;
			int RX = 0;
			int threshold = 15;
			while (1) {
				displayLCDNumber(0,1,SensorValue[drumPosEnc],1);
				if (vexRT[Btn8U]) {
					setDrumMotors(-127);
				} else if (vexRT[Btn8D]) {
					setDrumMotors(127);
				} else {
					setDrumMotors(0);
				}

				if (vexRT[Btn7L] && DEBUG_ENABLE) {
					resetDrumPosition();
				} else if (vexRT[Btn7R] && DEBUG_ENABLE) {
					moveCatapultDrumDist(500);
				}


				//for deadzones; when the joystick value for an axis is below the threshold, the motors controlled by that joystick will not move in that direction
				LY = (abs(vexRT[Ch3]) > threshold) ? vexRT[Ch3] : 0;
				LX = (abs(vexRT[Ch4]) > threshold) ? vexRT[Ch4] : 0;
				RY = (abs(vexRT[Ch2]) > threshold) ? vexRT[Ch2] : 0;
				RX = (abs(vexRT[Ch1]) > threshold) ? vexRT[Ch1] : 0;
				motor[lDriveFront] = LY + LX;
				motor[lDriveBack] = LY - LX;
				motor[rDriveFront] = RY + RX;
				motor[rDriveBack] = RY - RX;
				wait1Msec(25);
		}
	}
}
