#pragma config(Sensor, dgtl1,  drumLock,       sensorDigitalOut)
#pragma config(Sensor, dgtl2,  drumPosEnc,     sensorQuadEncoder)
#pragma config(Motor,  port1,           lDrive1,       tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           lDrive2,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           rCatapult1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rCatapult2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rCatapult3,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lCatapult1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lCatapult2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lCatapult3,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rDrive1,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rDrive2,       tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setDrumMotors (float power) {
		motor[lCatapult1] = power;
		motor[lCatapult2] = power;
		motor[lCatapult3] = power;
		motor[rCatapult1] = power;
		motor[rCatapult2] = power;
		motor[rCatapult3] = power;
}

void setLeftDtMotors(float power) {
	motor[lDrive1] = power;
	motor[lDrive2] = power;
}

void setRightDtMotors(float power) {
	motor[rDrive1] = power;
	motor[rDrive2] = power;
}

//full rev = 360*7
//FORWARD ONLY - this function is not written to handle negative values yet and the drum will only go forward
//automatically releases ratchet first
void moveCatapultDrumDist (int encoderClicks) {
	SensorValue[drumLock] = 1;
	SensorValue[drumPosEnc] = 0;
	wait1Msec(250);
	time1[T1] = 0;
	writeDebugStreamLine("Start time: %f", time1[T1]);
	while(abs(SensorValue[drumPosEnc]) < encoderClicks) {
		setDrumMotors(127);
	}
	writeDebugStreamLine("End time: %f", time1[T1]);
	setDrumMotors(0);
}

task main()
{
	//moveCatapultDrumDist(360*7);
	while (1) {
		setLeftDtMotors(vexRT[Ch3]);
		setRightDtMotors(vexRT[Ch2]);
		wait1Msec(25);
	}
}
