#pragma config(Motor,  port2,           lDriveFront,   tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           lDriveBack,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           leftDump12,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           leftDump3,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           rightDump3,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightDump12,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           rDriveBack,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rDriveFront,   tmotorVex393TurboSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setDumpMotors(int power) {
	motor[leftDump12] = power;
	motor[leftDump3] = power;
	motor[rightDump12] = power;
	motor[rightDump3] = power;
}

void setLeftDtMotors(int power) {
	motor[lDriveFront] = power;
	motor[lDriveBack] = power;
}

void setRightDtMotors(int power) {
	motor[rDriveFront] = power;
	motor[rDriveBack] = power;
}

task main()
{
	int threshold = 15; //for joystick deadzones
	while(1) {
		setDumpMotors(vexRT[Btn6U]*127 - vexRT[Btn6D]*127);
		if (abs(vexRT[Ch3]) > threshold) { setLeftDtMotors(vexRt[Ch3]); }
		else { setLeftDtMotors(0); }
		if (abs(vexRT[Ch2]) > threshold) { setRightDtMotors(vexRt[Ch2]); }
		else { setRightDtMotors(0); }
	}


}
