#pragma config(Motor,  port1,           leftIntake,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LFB1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LFB2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           FL,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           FR,            tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           BR,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           BL,            tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           RFB1,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RFB2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightIntake,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------

By Wyatt Johnson. Used on robot 1900A (Pinky?) of the Woodward Academy Robotics Team

Motor Pin Diagram:
1. Left Intake Motor
2. Left Four-Bar Motor 1
3. Left Four-Bar Motor 2
4. Front Left Drivetrain Motor
5. Front Right Drivetrain Motor
6. Back Right Drivetrain Motor
7. Back Left Drivetrain Motor
8. Right Four-Bar Motor 1
9. Right Four-Bar Motor 2
10. Right Intake Motor

--------------------------------------------------------

Motion / Mechanics Notes

Entire left side is reversed so that robot can go forward
List (FL Speed, BL speed, BR speed, FR) - remember FL and BL are reversed
Forward: 127, 127, 127, 127 - both joysticks forward
Backwards: -127, -127, -127, -127 - both joysticks backwards
Strafe Left: -127, 127, 127, -127 - both joysticks left
Strafe Right: 127, -127, -127, 127 - both joysticks right
Rotate Left: -127, -127, 127, 127 - left joystick down right joystick up
Rotate Right: 127, 127, -127,-127 - left joystick up right joystick down

Intake

6U - intake stars, both intakes 127
6D - release stars? Intake goes opposite direction

Four-Bar




------------------------------------------------------*/

int threshold = 15; //minimum joystick value
int fBPower = 75;
int intakePwr = 127;

task main()
{
	int LY = 0;
	int LX = 0;
	int RY = 0;
	int RX = 0;

	while(true )
	{
		/*
		Ternary Statement: value = (true boolean) ? (false boolean) : value
		If the absolute value of one of these vexRT Channels is greater than the threshold, assign the value
		If it is NOT greater than threshold, make it 0
		*/
		LX = (abs(vexRT[Ch4]) > threshold) ? vexRT[Ch4] : 0;
		LY = (abs(vexRT[Ch3]) > threshold) ? vexRT[Ch3] : 0;
		RY = (abs(vexRT[Ch2]) > threshold) ? vexRT[Ch2] : 0;
		RX = (abs(vexRT[Ch1]) > threshold) ? vexRT[Ch1] : 0;

		motor[FL] = LY + LX;
		motor[FR] = RY - RX;
		motor[BR] = RY + RX;
		motor[BL] = LY - LX;

		//Intake Controls

		if(vexRT[Btn6U] == 1){ //if Button 6U is being pressed, intake stars
			motor[rightIntake] = intakePwr;
			motor[leftIntake] = intakePwr;
		}
		else if(vexRT[Btn6D] == 1){ //if button 6D
			motor[rightIntake] = -intakePwr;
			motor[leftIntake] = -intakePwr;
		}
		else if ((vexRT[Btn6D] == 0) && (vexRT[Btn6U] == 0)){ //if neither butto is begin pressed, turn the motor off
		motor[rightIntake] = 0;
		motor[leftIntake] = 0;
		}

		//Four-Bar Code
		if ((vexRT[Btn5U]) == 1){
		motor[LFB1] = fBPower;
		motor[LFB2] = fBPower;
		motor[RFB1] = fBPower;
		motor[RFB2] = fBPower;

		}
		else if ((vexRT[Btn5D]) == 1){
		motor[LFB1] = -fBPower;
		motor[LFB2] = -fBPower;
		motor[RFB1] = -fBPower;
		motor[RFB2] = -fBPower;
		}
		else if ((vexRT[Btn5D] == 0) && (vexRT[Btn5U] == 0) ){
		motor[LFB1] = 0;
		motor[LFB2] = 0;
		motor[RFB1] = 0;
		motor[RFB2] = 0;

		}
	}
}
