#pragma config(Motor,  port4,           FL,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           FR,            tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           BR,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           BL,            tmotorVex393TurboSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------

Motor Pin Diagram:

FL - front left motor
FR - front right motor
BR - back right motor
BL - back left motor

Motion / Mechanics Notes

Entire left side is reversed so that robot can go forward
List (FL Speed, BL speed, BR speed, FR) - remember FL and BL are reversed
Forward: 127, 127, 127, 127 - both joysticks forward
Backwards: -127, -127, -127, -127 - both joysticks backwards
Strafe Left: -127, 127, 127, -127 - both joysticks left
Strafe Right: 127, -127, -127, 127 - both joysticks right
Rotate Left: -127, -127, 127, 127 - left joystick down right joystick up
Rotate Right: 127, 127, -127,-127 - left joystick up right joystick down


------------------------------------------------------*/

int threshold = 15;

task main()
{
	int LY = 0;
	int LX = 0;
	int RY = 0;
	int RX = 0;

  while(true )
  {
  	/*
  	Ternary Statement: value = (true boolean) ? (false boolean) : value
  	If the absolute value of one of these vexRT Channels is greater than the threshold, assign the value
  	If it is NOT greater than threshold, make it 0
  	*/
  	LX = (abs(vexRT[Ch4]) > threshold) ? vexRT[Ch4] : 0;
  	LY = (abs(vexRT[Ch3]) > threshold) ? vexRT[Ch3] : 0;
  	RY = (abs(vexRT[Ch2]) > threshold) ? vexRT[Ch2] : 0;
  	RX = (abs(vexRT[Ch1]) > threshold) ? vexRT[Ch1] : 0;

  	motor[FL] = LY + LX;
  	motor[FR] = RY - RX;
  	motor[BR] = RY + RX;
  	motor[BL] = LY - LX;

	}
}
