#pragma config(Motor,  port1,           leftIntake,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LFB1,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LFB2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FL,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           FR,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           BR,            tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           BL,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           RFB1,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RFB2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightIntake,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------

By Wyatt Johnson. Used on robot 1900A (Pinky?) of the Woodward Academy Robotics Team

Motor Pin Diagram:
1. Left Intake Motor
2. Left Four-Bar Motor 1
3. Left Four-Bar Motor 2
4. Front Left Drivetrain Motor
5. Front Right Drivetrain Motor
6. Back Right Drivetrain Motor
7. Back Left Drivetrain Motor
8. Right Four-Bar Motor 1
9. Right Four-Bar Motor 2
10. Right Intake Motor

--------------------------------------------------------

Motion / Mechanics Notes

Entire left side is reversed so that robot can go forward
List (FL Speed, BL speed, BR speed, FR) - remember FL and BL are reversed
Forward: 127, 127, 127, 127 - both joysticks forward
Backwards: -127, -127, -127, -127 - both joysticks backwards
Strafe Left: -127, 127, 127, -127 - both joysticks left
Strafe Right: 127, -127, -127, 127 - both joysticks right
Rotate Left: -127, -127, 127, 127 - left joystick down right joystick up
Rotate Right: 127, 127, -127,-127 - left joystick up right joystick down

Intake

6U - intake stars, both intakes 127
6D - release stars? Intake goes opposite direction

Switch Values

	0 = all motors off
	1 = intake stars
	2 = reverse intake
	3 = extend four bar
	4 = retract four bar
	5 = launch catapult
	6 = reload catapult

------------------------------------------------------*/

int threshold = 15; //minimum joystick value
int controlValue = 0;

task main()
{
	int LY = 0;
	int LX = 0;
	int RY = 0;
	int RX = 0;

	while(true )
	{
		/*
		Ternary Statement: value = (true boolean) ? (false boolean) : value
		If the absolute value of one of these vexRT Channels is greater than the threshold, assign the value
		If it is NOT greater than threshold, make it 0
		*/
		LX = (abs(vexRT[Ch4]) > threshold) ? vexRT[Ch4] : 0;
		LY = (abs(vexRT[Ch3]) > threshold) ? vexRT[Ch3] : 0;
		RY = (abs(vexRT[Ch2]) > threshold) ? vexRT[Ch2] : 0;
		RX = (abs(vexRT[Ch1]) > threshold) ? vexRT[Ch1] : 0;

		motor[FL] = LY + LX;
		motor[FR] = RY - RX;
		motor[BR] = RY + RX;
		motor[BL] = LY - LX;

		//Intake Value Assigners
		//Intake Control Values
		if(vexRT[Btn6U] == 1){ //if Button 6U is being pressed, intake stars
			controlValue = 1;
		}
		else if(vexRT[Btn6D] == 1){ //if button 6D is pressed, reverse intake
			controlValue = 2;
		}
		//Four-Bar Code
		if ((vexRT[Btn5U]) == 1){ //If 5U is pressed, raise the four bar
		controlValue = 3;
		}
		else if ((vexRT[Btn5D]) == 1){ //if 5D is pressed, lower the four bar
		controlValue = 4;
		}
		else if ((vexRT[Btn8R]) == 1){ //if 8R is pressed, launch catapult
		controlValue = 5;
		}
		else if ((vexRT[Btn8D]) == 1){ //if 8D is pressed, reset / reload catapult
		controlValue = 6;
		}
		else if ((vexRT[Btn5D] == 0) && (vexRT[Btn5U] == 0) ){ //if no button is pressed, reset values
		controlValue = 0;

		}
		switch controlValue {
			case 0:
			motor[rightIntake] = 0;
			motor[leftIntake] = 0;
			motor[LFB1] = 0;
			motor[LFB2] = 0;
			motor[RFB1] = 0;
			motor[RFB2] = 0;
			motor[
			case 1: //intake stars
			motor[rightIntake] = 127;
			motor[leftIntake] = 127;

	}
}
