#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    AutonSelector,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  DRFL1,          sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  DRFR1,          sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  DRBR1,          sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  DRBL1,          sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  armLock,        sensorDigitalOut)
#pragma config(Sensor, dgtl10, liftLock,       sensorDigitalOut)
#pragma config(Sensor, dgtl11, FBBotLim,       sensorTouch)
#pragma config(Sensor, dgtl12, FBTopLim,       sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_6,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           FL,            tmotorVex393TurboSpeed_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           FR,            tmotorVex393TurboSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           LFBT,          tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_6)
#pragma config(Motor,  port4,           LFBB,          tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_5)
#pragma config(Motor,  port5,           leftLift,      tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_4)
#pragma config(Motor,  port6,           rightLift,     tmotorVex393_MC29, openLoop, driveRight, encoderPort, I2C_3)
#pragma config(Motor,  port7,           RFBB,          tmotorVex393_MC29, openLoop, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port8,           RFBT,          tmotorVex393_MC29, openLoop, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port9,           BR,            tmotorVex393TurboSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port10,          BL,            tmotorVex393TurboSpeed_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Contains variables and funtions for Alpha (1900A)

int threshold = 15;

void setFBMotors(int speed){ //automatically sets the four bar power (reduce clutter)
	motor[RFBT] = speed;
	motor[RFBB] = speed;
	motor[LFBT] = speed;
	motor[LFBB] = speed;

}

task main()
{



}
