#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           backLeft,      tmotorVex393TurboSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port4,           frontRight,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           backRight,     tmotorVex393TurboSpeed_MC29, openLoop, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){

		//Threshold Code (Prevent stalling)
		if (vexRT[Ch2] <= 15){
			motor[frontRight] = 0;
			motor[backRight] = 0;
			motor[frontLeft] = vexRT[Ch3];
			motor[backLeft] = vexRT[Ch3];
		}
		else if (vexRT[Ch3] = 0){
			motor[frontLeft] = 0;
			motor[backLeft] = 0;
			motor[frontRight] = vexRT[Ch2];
			motor[backRight] = vexRT[Ch2];
		}
		else {
			motor[frontLeft] = vexRT[Ch3];
			motor[backLeft] = vexRT[Ch3];
			motor[frontRight] = vexRT[Ch2];
			motor[backRight] = vexRT[Ch2];
		}

	}


}
