#pragma config(Sensor, dgtl7,  liftEnc,        sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  rDriveEnc,      sensorQuadEncoder)
#pragma config(Sensor, dgtl11, lDriveEnc,      sensorQuadEncoder)
#pragma config(Motor,  port1,           leftClaw,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           lDriveFront,   tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           rDriveFront,   tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           dumpTopY,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           dumpOutsideLeft, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           dumpOutsideRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           dumpBottomY,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lDriveBack,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           rDriveBack,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightClaw,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//1/10: claw (2 motors)
//2/3: front drivetrain motors (2 motors)
//4 and 7: 2 Y-offs, 1 motor from each side of lift (4 motors)
//5-6: 1 lift motor each from each side of lift (2 motors) through PE
//8/9: back drivetrain motors (2) through PE

//parameter is a float because sometimes this gets powers via a PID function
void setLeftDtMotors(float power) {
	motor[lDriveFront] = power;
	motor[lDriveBack] = power;
}

void setRightDtMotors(float power) {
	motor[rDriveFront] = power;
	motor[rDriveBack] = power;
}

void setDumpMotors(float power) {
	motor[dumpTopY] = power;
	motor[dumpBottomY] = power;
	motor[dumpOutsideLeft] = power;
	motor[dumpOutsideRight] = power;
}


task main()
{

	while(1) {
		setLeftDtMotors(vexRT[AccelX]);
		setRightDtMotors(vexRT[AccelY]);

	}


}
