#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightDrive,    tmotorVex393TurboSpeed_HBridge, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

{
task main()
	while(true){
	motor[rightDrive] = vexRT[Ch2]:
	motor[leftDrive] = vexRT[Ch3];
}


}
